version: '3.8'

services:
  web-app:
    container_name: tavoli-gdr
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3010:3000"
    volumes:
      - tavoli-data:/app/src/data
      - tavoli-uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/src/data/db.json
      - RESEND_API_KEY=${RESEND_API_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}

volumes:
  tavoli-data:
    name: tavoli-data
  tavoli-uploads:
    name: tavoli-uploads
